apiVersion: v2
name: qutil
description: >-
  Qvest DMF and MXL utility app. Serves the multiviewer and books the media
  functions it observes.
type: application
version: 1.0.0-rc.15 # x-release-please-version
appVersion: 1.0.0-rc.15 # x-release-please-version
kubeVersion: '>=1.28.0-0'
home: https://github.com/qvest-digital/dmf-app-qutil
sources:
  - https://github.com/qvest-digital/dmf-app-qutil
maintainers:
  - name: Qvest Digital
